version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: secret123
      MARIADB_DATABASE: laika
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpass
      MARIADB_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./laika.sql:/docker-entrypoint-initdb.d/01-laika.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb       # name of the MariaDB service
      PMA_USER: devuser       # the user you defined
      PMA_PASSWORD: devpass   # the password you set
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  db_data:
