CREATE DATABASE IF NOT EXISTS laika;

USE laika;

CREATE TABLE laika_user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(150) UNIQUE NOT NULL,
	password_hash CHAR(60) NOT NULL,
	email VARCHAR(254) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
