import { StyleSheet } from 'react-native';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#efedeaff',
    fontWeight: 'bold',
  },
  scrollContainer: {
    padding: 20,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 15,
    fontWeight: 'bold',
  },
  label: {
    fontSize: 16,
    color: '#000',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  asterisk: {
    color: 'red',
  },
  pickerContainer: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    marginBottom: 15,
    overflow: 'hidden', // Ensures the Picker respects the border radius
  },
  picker: {
    backgroundColor: 'transparent', // To see the container's background
    borderWidth: 0, // Handled by container
    fontWeight: 'bold',
  },
  imageContainer: {
    alignItems: 'center',
    marginBottom: 15,
    fontWeight: 'bold',
  },
  imageButton: {
    backgroundColor: '#000',
    padding: 12,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 20,
    fontWeight: 'bold',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  imageButtonText: {
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
  },
  previewImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
    margin: 5,
  },
  previewContainer: {
    flexDirection: 'row',
  },
  previewImageWrapper: {
    position: 'relative',
  },
  deleteImageButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: 'white',
    borderRadius: 12,
  },
  switchContainer: {
    justifyContent: 'space-between',
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
    fontWeight: 'bold',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  switchLabel: {
    fontSize: 16,
    color: '#333',
    fontWeight: 'bold',
    marginBottom: 10,
    flex: 1,
  },
  submitButton: {
    backgroundColor: '#b04f4f',
    padding: 15,
    borderRadius: 10,
    marginTop: 20,
    fontWeight: 'bold',
  },
  submitButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  logoApp: {
    alignSelf: 'center',
    marginBottom: 20,
  },
  inputMultiline: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 15,
    minHeight: 100,
    textAlignVertical: 'top',
    fontWeight: 'bold',
  },
  mapContainer: {
    width: '100%',
    height: 250,
    marginBottom: 15,
    borderRadius: 5,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ddd',
    fontWeight: 'bold',
  },
  map: {
    width: '100%',
    height: 220,
    fontWeight: 'bold',
  },
  addressText: {
    padding: 5,
    fontSize: 12,
    backgroundColor: '#f8f8f8',
    color: '#333',
    fontWeight: 'bold',
  },
  loadingText: {
    padding: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  typeHint: {
    fontSize: 14,
    color: 'red',
    fontStyle: 'italic',
    marginBottom: 15,
    textAlign: 'center',
    paddingHorizontal: 10,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  photoInstructionsContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    margin: 20,
    alignItems: 'center',
    maxWidth: 350,
    fontWeight: 'bold',
  },
  photoInstructionsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  photoInstructionsText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 10,
    lineHeight: 22,
    fontWeight: 'bold',
  },
  photoInstructionsSubtext: {
    fontSize: 14,
    color: '#333',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  placeholderImage: {
    width: 200,
    height: 200,
    borderRadius: 10,
    marginBottom: 20,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  photoInstructionsButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    fontWeight: 'bold',
  },
  photoInstructionsButton: {
    backgroundColor: '#b04f4f',
    padding: 12,
    borderRadius: 5,
    flex: 1,
    marginRight: 5,
    alignItems: 'center',
    fontWeight: 'bold',
  },
  photoInstructionsCancelButton: {
    backgroundColor: '#777',
    padding: 12,
    borderRadius: 5,
    flex: 1,
    marginLeft: 5,
    alignItems: 'center',
    fontWeight: 'bold',
  },
  photoInstructionsButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  customPickerButton: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontWeight: 'bold',
  },
  colorPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    fontWeight: 'bold',
  },
  customPickerText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 10,
    fontWeight: 'bold',
    flex: 1,
  },
  colorOptionsContainer: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    marginBottom: 15,
    maxHeight: 200,
    fontWeight: 'bold',
  },
  colorOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    fontWeight: 'bold',
  },
  colorSquare: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    marginRight: 10,
    fontWeight: 'bold',
  },
  colorOptionText: {
    fontSize: 16,
    color: '#333',
    flex: 1,
    fontWeight: 'bold',
  },
  aiHint: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 5,
    textAlign: 'center',
    paddingHorizontal: 10,
    fontWeight: 'bold',
  },
  ageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    fontWeight: 'bold',
  },
  ageInput: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 10,
    fontWeight: 'bold',
  },
  ageUnitPickerContainer: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    overflow: 'hidden',
  },
  ageUnitPicker: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 0,
    fontWeight: 'bold',
  },
  sizePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  sizePicker: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  sizeIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'grey',
    marginHorizontal: 15,
  },
  pickerWithIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    width: '100%',
  },
  pickerIcon: {
    marginHorizontal: 10,
  },
  customPickerModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    margin: 20,
    alignItems: 'center',
    maxWidth: 350,
    width: '90%',
  },
  customPickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    width: '100%',
  },
  customPickerOptionIcon: {
    marginRight: 15,
  },
  customPickerOptionText: {
    fontSize: 18,
    color: '#333',
    fontWeight: 'bold',
  },
});

export default style;